version: "3.8"
services:
  app:
    container_name: oas-platform-hotels-master-api
    build:
      context: .
      dockerfile: ./build/Dockerfile.local
      args:
        ACCESS_TOKEN:
    volumes:
      - ./:/app/
    working_dir: /app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
