package repositories

import (
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// gorm.Model definition
type Hotels struct {
	gorm.Model
	Name                  []*HotelName        `gorm:"foreignKey:HotelID"`
	Description           []*HotelDescription `gorm:"foreignKey:HotelID"`
	Status                bool
	CountryCode           string
	StateCode             string
	DestinationCode       string
	ZoneCode              string
	Coordinates           datatypes.JSON
	CategoryCode          string
	CategoryGroupCode     string
	ChainCode             string
	AccommodationTypeCode string
	BoardCodes            []string
	SegmentCodes          []string
}

type AutoGenerated struct {
	Code int `json:"code"`
	Name struct {
		Content string `json:"content"`
	} `json:"name"`
	Description struct {
		Content string `json:"content"`
	} `json:"description"`
	CountryCode     string `json:"countryCode"`
	StateCode       string `json:"stateCode"`
	DestinationCode string `json:"destinationCode"`
	ZoneCode        int    `json:"zoneCode"`
	Coordinates     struct {
		Longitude float64 `json:"longitude"`
		Latitude  float64 `json:"latitude"`
	} `json:"coordinates"`
	CategoryCode          string   `json:"categoryCode"`
	CategoryGroupCode     string   `json:"categoryGroupCode"`
	ChainCode             string   `json:"chainCode"`
	AccommodationTypeCode string   `json:"accommodationTypeCode"`
	BoardCodes            []string `json:"boardCodes"`
	SegmentCodes          []int    `json:"segmentCodes"`
	AmenityCodes          []int    `json:"amenityCodes"`
	Address               struct {
		Content string `json:"content"`
		Street  string `json:"street"`
		Number  string `json:"number"`
	} `json:"address"`
	PostalCode string `json:"postalCode"`
	City       struct {
		Content string `json:"content"`
	} `json:"city"`
	Email      string `json:"email"`
	License    string `json:"license"`
	Web        string `json:"web"`
	LastUpdate string `json:"lastUpdate"`
	S2C        string `json:"S2C"`
	Ranking    int    `json:"ranking"`
}
