package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"context"
	"fmt"

	"github.com/oasis-prime/oas-platform-hotels-master-api/graph/model"
)

// GetPromotion is the resolver for the getPromotion field.
func (r *queryResolver) GetPromotion(ctx context.Context, input model.PromotionInput) (*model.PromotionData, error) {
	panic(fmt.Errorf("not implemented: GetPromotion - getPromotion"))
}
