// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hotel struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type NewHotel struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
