app:
  env: APP_ENV
  debug: APP_DEBUG
  port: APP_PORT
database:
  name: DATABASE_NAME
  user: DATABASE_USER
  pwd: DATABASE_PWD
  instance:
    connection:
      name: DATABASE_INSTANCE_CONNECTION_NAME
  socket:
    dir: DATABASE_SOCKET_DIR
jwt:
  secret: JWT_SECRET
  expirationdelta: JWT_EXPIRATIONDELTA
redis:
  address: REDIS_ADDRESS
  password: REDIS_PASSWORD
  db: REDIS_DB
hotelbeds:
  endpoint: HOTELBEDS_ENDPOINT
  secureendopint: HOTELBEDS_SECUREENDOPINT
  key: HOTELBEDS_KEY
  secret: HOTELBEDS_SECRET
  format: HOTELBEDS_FORMAT
